[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.7",
    "fastapi>=0.115.12",
    "openai>=1.84.0",
    "pydantic>=2.11.5",
    "uvicorn>=0.34.3",
]
